# Generated by Django 5.2.6 on 2026-07-07 10:58

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('service', models.CharField(max_length=255, verbose_name='Услуга')),
                ('page_slug', models.CharField(max_length=120, verbose_name='Страница-источник')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=core.models.application_photo_upload_to, verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('h1', models.CharField(max_length=255, verbose_name='H1')),
                ('eyebrow', models.CharField(blank=True, max_length=255, verbose_name='Короткий подзаголовок')),
                ('subtitle', models.TextField(blank=True, verbose_name='Основной подзаголовок')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO title')),
                ('seo_description', models.TextField(blank=True, verbose_name='SEO description')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to=core.models.hero_image_upload_to, verbose_name='Hero-изображение')),
                ('hero_image_alt', models.CharField(blank=True, max_length=255, verbose_name='Alt hero-изображения')),
                ('hero_advantages', models.TextField(blank=True, verbose_name='Преимущества в hero')),
                ('right_card_items', models.JSONField(blank=True, default=list, verbose_name='Пункты правой карточки')),
                ('cta_primary_text', models.CharField(default='Вызвать бригаду', max_length=120, verbose_name='Текст основной кнопки')),
                ('cta_secondary_text', models.CharField(default='Рассчитать стоимость', max_length=120, verbose_name='Текст второй кнопки')),
                ('service_section_title', models.CharField(default='Наши услуги', max_length=255, verbose_name='Заголовок секции услуг')),
                ('features_section_title', models.CharField(default='Что мы делаем', max_length=255, verbose_name='Заголовок секции действий')),
                ('feature_items', models.TextField(blank=True, verbose_name='Список действий')),
                ('work_examples_section_title', models.CharField(default='Наши работы', max_length=255, verbose_name='Заголовок секции работ')),
                ('advantages_section_title', models.CharField(default='Почему выбирают нас', max_length=255, verbose_name='Заголовок секции преимуществ')),
                ('steps_section_title', models.CharField(default='Как мы работаем', max_length=255, verbose_name='Заголовок секции этапов')),
                ('equipment_section_title', models.CharField(default='Наше профессиональное оборудование', max_length=255, verbose_name='Заголовок секции оборудования')),
                ('about_section_title', models.CharField(default='О компании', max_length=255, verbose_name='Заголовок секции о компании')),
                ('guarantee_title', models.CharField(default='Гарантия качества до 30 дней', max_length=255, verbose_name='Заголовок блока гарантии')),
                ('guarantee_text', models.TextField(blank=True, verbose_name='Текст блока гарантии')),
                ('guarantee_items', models.TextField(blank=True, verbose_name='Список гарантий')),
                ('is_active', models.BooleanField(default=True, verbose_name='Страница активна')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('application_email', models.EmailField(blank=True, default='molniya@profcleaning-comp.ru', max_length=254, verbose_name='Email для заявок')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('work_time', models.CharField(blank=True, max_length=128, verbose_name='Режим работы')),
                ('metrika_code', models.TextField(blank=True, verbose_name='Код Яндекс.Метрики')),
                ('policy_text', models.TextField(blank=True, verbose_name='Текст политики')),
                ('telegram_chat_id', models.CharField(blank=True, max_length=128, verbose_name='Telegram chat ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Логотип')),
                ('favicon', models.FileField(blank=True, null=True, upload_to='site/', verbose_name='Favicon')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=10, verbose_name='Порядок')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.equipment_image_upload_to, verbose_name='Изображение')),
                ('image_alt', models.CharField(blank=True, max_length=255, verbose_name='Alt изображения')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='core.page')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'ordering': ('order', 'pk'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=10, verbose_name='Порядок')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('icon', models.CharField(blank=True, default='check', max_length=64, verbose_name='Иконка')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advantages', to='core.page')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
                'ordering': ('order', 'pk'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=10, verbose_name='Порядок')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.service_image_upload_to, verbose_name='Изображение')),
                ('image_alt', models.CharField(blank=True, max_length=255, verbose_name='Alt изображения')),
                ('icon', models.CharField(blank=True, default='check', max_length=64, verbose_name='Иконка')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.page')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ('order', 'pk'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=10, verbose_name='Порядок')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('icon', models.CharField(blank=True, default='check', max_length=64, verbose_name='Иконка')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.page')),
            ],
            options={
                'verbose_name': 'Этап',
                'verbose_name_plural': 'Этапы',
                'ordering': ('order', 'pk'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=10, verbose_name='Порядок')),
                ('before_image', models.ImageField(blank=True, null=True, upload_to=core.models.before_work_example_upload_to, verbose_name='Фото до')),
                ('before_alt', models.CharField(blank=True, max_length=255, verbose_name='Alt для фото до')),
                ('after_image', models.ImageField(blank=True, null=True, upload_to=core.models.after_work_example_upload_to, verbose_name='Фото после')),
                ('after_alt', models.CharField(blank=True, max_length=255, verbose_name='Alt для фото после')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_examples', to='core.page')),
            ],
            options={
                'verbose_name': 'Пример работы',
                'verbose_name_plural': 'Примеры работ',
                'ordering': ('order', 'pk'),
                'abstract': False,
            },
        ),
    ]
