# Generated by Django 5.2.15 on 2026-07-07 19:22

import django.db.models.deletion
from django.db import migrations, models


def migrate_application_relations(apps, schema_editor):
    Application = apps.get_model("core", "Application")
    Page = apps.get_model("core", "Page")
    Service = apps.get_model("core", "Service")

    for application in Application.objects.all().iterator():
        page = Page.objects.filter(slug=application.legacy_page_slug).first()
        service = None

        if page:
            service = Service.objects.filter(page=page, title=application.legacy_service).first()

        Application.objects.filter(pk=application.pk).update(
            page_id=page.pk if page else None,
            service_id=service.pk if service else None,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_advantage_groups"),
    ]

    operations = [
        migrations.RenameField(
            model_name="application",
            old_name="service",
            new_name="legacy_service",
        ),
        migrations.RenameField(
            model_name="application",
            old_name="page_slug",
            new_name="legacy_page_slug",
        ),
        migrations.AddField(
            model_name="application",
            name="page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applications",
                to="core.page",
                verbose_name="Страница-источник",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applications",
                to="core.service",
                verbose_name="Услуга",
            ),
        ),
        migrations.RunPython(migrate_application_relations, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="application",
            name="legacy_page_slug",
        ),
        migrations.RemoveField(
            model_name="application",
            name="legacy_service",
        ),
    ]
