# Generated by Django 5.2.6 on 2026-07-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_telegramsubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=128, verbose_name='Telegram username'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='WhatsApp'),
        ),
    ]
